# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\REM\ui\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1223, 995)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_widget = QtWidgets.QWidget(self.centralwidget)
        self.left_widget.setObjectName("left_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.elementsTableWidget = QtWidgets.QTableWidget(self.left_widget)
        self.elementsTableWidget.setObjectName("elementsTableWidget")
        self.elementsTableWidget.setColumnCount(0)
        self.elementsTableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.elementsTableWidget)
        self.compoundTableWidget = QtWidgets.QTableWidget(self.left_widget)
        self.compoundTableWidget.setObjectName("compoundTableWidget")
        self.compoundTableWidget.setColumnCount(0)
        self.compoundTableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.compoundTableWidget)
        self.widget = QtWidgets.QWidget(self.left_widget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadBtn = QtWidgets.QPushButton(self.widget)
        self.loadBtn.setObjectName("loadBtn")
        self.horizontalLayout.addWidget(self.loadBtn)
        self.saveBtn = QtWidgets.QPushButton(self.widget)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout.addWidget(self.saveBtn)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout_2.addWidget(self.left_widget)
        self.right_widget = QtWidgets.QWidget(self.centralwidget)
        self.right_widget.setObjectName("right_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.right_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.compoundListWidget = QtWidgets.QListWidget(self.right_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compoundListWidget.sizePolicy().hasHeightForWidth())
        self.compoundListWidget.setSizePolicy(sizePolicy)
        self.compoundListWidget.setMaximumSize(QtCore.QSize(200, 50000))
        self.compoundListWidget.setObjectName("compoundListWidget")
        self.verticalLayout.addWidget(self.compoundListWidget)
        self.compoundLineEdit = QtWidgets.QLineEdit(self.right_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compoundLineEdit.sizePolicy().hasHeightForWidth())
        self.compoundLineEdit.setSizePolicy(sizePolicy)
        self.compoundLineEdit.setObjectName("compoundLineEdit")
        self.verticalLayout.addWidget(self.compoundLineEdit)
        self.addBtn = QtWidgets.QPushButton(self.right_widget)
        self.addBtn.setObjectName("addBtn")
        self.verticalLayout.addWidget(self.addBtn)
        self.removeBtn = QtWidgets.QPushButton(self.right_widget)
        self.removeBtn.setObjectName("removeBtn")
        self.verticalLayout.addWidget(self.removeBtn)
        self.horizontalLayout_2.addWidget(self.right_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadBtn.setText(_translate("MainWindow", "Load from Clipboard"))
        self.saveBtn.setText(_translate("MainWindow", "Save as Excel"))
        self.addBtn.setText(_translate("MainWindow", "Add"))
        self.removeBtn.setText(_translate("MainWindow", "Remove"))
